export const banner = `MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMWNXMkxdoooooooooooodkOKNWWMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMWNKko1111oodxkOMMMMMMOkxdo1111odOXWWMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMWNKx1c1odkKNWMMMMMMMMMMMMMMMMMMWXMxo1ccokXWMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMWNMdc,'1MXO1cOWMMMMMMMMMMMMMMMMMMMMXocdKXk;':1xKWMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMWXxccoo,.1Kd..oXMMMMMM-LASMETA-MMMMMMWk,.:Mk,.1x1:1ONWMMMMMMMMMMMMM
MMMMMMMMMMMWKd:ckXMO'.;c,'oNWKMXMMMMMMMMMMMMMMMNMMNWO;.:c'.1NWKd:cxXWMMMMMMMMMMM
MMMMMMMMMWKo:1OWMMMXc..',cOK1',kWMMMMMMMMMMMMMMX1';kXd,,..'kWMMMNxc:kNMMMMMMMMMM
MMMMMMMWNx:cOWMMMMMMXx;..;1:.:OWMMWWWMMMMMMWWWMMXo''cc'.'1MWMMMMMMNx:cOWMMMMMMMM
MMMMMMWM1;xNMMMMMMMMMMKc...';kWMNxccOWMMMMXo:oMWMX1'...,kWMMMMMMMMMMXo;dXWMMMMMM
MMMMMNk;cKWMMMMMMMMMMMWKd;..'ckkc''oXMMMMMWk;.;dOd,..,1ONMMMMMMMMMMMMWk;cMWMMMMM
MMMMNx;oNMMMMMMMMMMMMMMccxko,.',''1XMMMMMMMWk;'',.'cxko:xWMMMMMMMMMMMMMM::OWMMMM
MMMNx,dNMMMMMMMMMMMMMMNd'':1:',,'.1NMMMMMMMMk,.,;',1c,.:MWMMMMMMMMMMMMMMKc;OWMMM
MMWk,oNMMMMWXXXNWWWWWNWNMd1:,.','.'xWMMMMMMK:..,'.';cokXWNNWWWWNXXKXMMMMMK::MWMM
MWM;cXMMMMMM1cc11111odddxOXNK:..'..'kWMMMMXc......xNNKkddddo1111cccxNMMMMMM;cXMM
MX1;MMMMMMMNko:,,'...'c1c:coo:,cooo1dkOOOOxoooo1:;1d1:c11;....,,;1dKWMMMMMWd,xWM
Wk,oWMMMMMMMWKxc;,,'...,od1;;okOMMMOOOkkkkOOOMMMMxc,cddc....',;:oOXWMMMMMMMX::KM
N1,MMMMMMMMMMMNMx1c:;;,';dxdxkxxddooooooooooooddxkkddx1,',;::coOXWMMMMMMMMMWd,xW
K;:XMMMMMMMMMMMMWXMkddoooo:;,''''.'''''''''''...'',,;1dooodxOKNWMMMMMMMMMMMMO,1N
O,oWMMMMMMMMMMMMMMMWXKMMx;,;:cc:;:::c11111ccc:;:cc::;,1MMKXNMMMMMMMMMMMMMMMMX::X
k,dWMMMMMMMMMMMMMMMMMMMWkod;..;oo1oodxxxxxddxo1d1'.'1odKMMMMMMMMMMMMMMMMMMMMX:;K
k,dWMMMMMMMMMMMMMMMMMMMWOxx;..,o1::;;;:;;;;;::co:..'oxxXMMMMMMMMMMMMMMMMMMMMX:;K
O,1WMMMMMMMMMMMMMMMMMMMMM1:ccooc;'';1dxxxxoc,'':oo1cc:xWMMMMMMMMMMMMMMMMMMMMK;:X
K::XMMMMMMMMMMMMMMMMMMMMWO:,,''.';oodOkkkOkdoc,.'''';dXMMMMMMMMMMMMMMMMMMMMMO,1N
N1,OMMMMMMMMMMMMMMMMMMMMMNkdddddxOd;1kMMMMx;ckkxdddddKMMMMMMMMMMMMMMMMMMMMMWo,kW
WO,1NMMMMMMMMMMMMMMMMMMMMWkokOOOOd:;:c1o11c:;1kOOOkdoKMMMMMMMMMMMMMMMMMMMMMK;:XM
MN1,OMMMMMMMMMMMMMMMMMMMMMXockOOkoc;'.....:::1xOOko:kWMMMMMMMMMMMMMMMMMMMMWo,kWM
MMK::KMMMMMMMMMMMMMMMMMMMMWd.,dOxod1;'....,:dddOx:.;KMMMMMMMMMMMMMMMMMMMMWk,oNMM
MMWO;cXMMMMMMMMMMMMMMMMMMMMx. .:1cxXk;....oKKo11.  :XMMMMMMMMMMMMMMMMMMMMO;cKMMM
MMMWk;1XMMMMMMMMMMMMMMMMMMMx'.....cOOx1ccoOMk:...'.cXMMMMMMMMMMMMMMMMMMWO;cKMMMM
MMMMWO;cMMMMMMMMMMMMMMMMMMNo',:,...:dkxdxxx1,..';;':MMMMMMMMMMMMMMMMMMWk:1KWMMMM
MMMMMWMc;kNMMMMMMMMMMMMMWOc'',cdo:,..',,,,'.';1do;,,;kNMMMMMMMMMMMMMMWXMMNMMMMMM
MMMMMMMXd;1KWMMMMMMMMMXk:..'1c;oOkx1;;;;,,,:okOOc:1;..;dKWMMMMMMMMMWKXWMWWMMMMWM
MMMMMMMMWM1;dKWMMMMNO1,.,:;1kk1:dOOkddkxddxkOOOocdko;;:,,1kKWMMMMWMc1KMMNXXWMMWM
MMMMMMMMMMNOc:oMNKx:.  .1o1dkkkocdkkkkkOOOkkxkd1xOkxo1x1..':dMNNO1:oKWMMWNNWMMMM
MMMMMMMMMMMMNM1:;'..    ,oxkkkkkdoxkkkkkkkxdoooxkkkkxxo'  ..',;::dKWMMWWMMWMMWMM
MMMMMMMMMMMMMMWXx:..     ,oOOOOkkxxkxxxxxxdo1oxkkOOxo;.     .,1ONMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMWKxc,.   .:dOOOkkxxooxxxxo1oxkOOxc'.   ..,1OXWMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMWNMx1;'..,codxxxocoxxdccdxxo:. ..,:okKNWMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMWWXMkd11cccc:;;;;;,;:ccccodOKNWMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNXXKKKKKXXXNWWMMMMMMMMM@denizumutdereliMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM`;